import { ElementCategory, ElementState, ElementType } from '../types/Element';

const createMockElements = (): ElementType[] => {
  const elements: ElementType[] = [
    {
      name: { value: 'Hydrogen', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'H', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 1, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 1.008, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.NONMETALS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Hydrogen is the most abundant chemical substance in the universe.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.GAS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: -259.16, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: -252.87, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [1], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Fuel, Rocket propellant', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Discovered by Henry Cavendish in 1766', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Hydrogen is the most abundant element in the universe.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 1,
      period: 1,
    },
    {
      name: { value: 'Helium', link: 'https://www.chemblink.com/structure/2_2_0-0.html' },
      symbol: { value: 'He', link: 'https://www.chemblink.com/structure/2_2_0-0.html' },
      atomicNumber: { value: 2, link: 'https://www.chemblink.com/structure/2_2_0-0.html' },
      atomicWeight: { value: 4.0026, link: 'https://www.chemblink.com/structure/2_2_0-0.html' },
      category: { value: ElementCategory.NOBLE_GASES, link: 'https://www.chemblink.com/structure/2_2_0-0.html' },
      description: { value: 'Helium is a colorless, odorless, tasteless, inert, monatomic gas that heads the noble gas group.', link: 'https://www.chemblink.com/structure/2_2_0-0.html' },
      stateAtRoomTemp: { value: ElementState.GAS, link: 'https://www.chemblink.com/structure/2_2_0-0.html' },
      meltingPoint: { value: -272.2, link: 'https://www.chemblink.com/structure/2_2_0-0.html' },
      boilingPoint: { value: -268.93, link: 'https://www.chemblink.com/structure/2_2_0-0.html' },
      electronConfiguration: { value: [2], link: 'https://www.chemblink.com/structure/2_2_0-0.html' },
      uses: { value: 'Used in cryogenics, cooling superconducting magnets', link: 'https://www.chemblink.com/structure/2_2_0-0.html' },
      history: { value: 'Discovered in 1895 by Sir William Ramsay', link: 'https://www.chemblink.com/structure/2_2_0-0.html' },
      interestingFacts: { value: 'Helium is the second most abundant element in the observable universe.', link: 'https://www.chemblink.com/structure/2_2_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/2_2_0-0.html',
      group: 18,
      period: 1,
    },
    {
      name: { value: 'Lithium', link: 'https://www.chemblink.com/structure/3_3_0-0.html' },
      symbol: { value: 'Li', link: 'https://www.chemblink.com/structure/3_3_0-0.html' },
      atomicNumber: { value: 3, link: 'https://www.chemblink.com/structure/3_3_0-0.html' },
      atomicWeight: { value: 6.94, link: 'https://www.chemblink.com/structure/3_3_0-0.html' },
      category: { value: ElementCategory.ALKALI_METALS, link: 'https://www.chemblink.com/structure/3_3_0-0.html' },
      description: { value: 'Lithium is a chemical element with the symbol Li and atomic number 3.', link: 'https://www.chemblink.com/structure/3_3_0-0.html' },
      stateAtRoomTemp: { value: ElementState.SOLID, link: 'https://www.chemblink.com/structure/3_3_0-0.html' },
      meltingPoint: { value: 180.54, link: 'https://www.chemblink.com/structure/3_3_0-0.html' },
      boilingPoint: { value: 1590, link: 'https://www.chemblink.com/structure/3_3_0-0.html' },
      electronConfiguration: { value: [2, 1], link: 'https://www.chemblink.com/structure/3_3_0-0.html' },
      uses: { value: 'Used in rechargeable batteries for mobile phones, laptops, digital cameras.', link: 'https://www.chemblink.com/structure/3_3_0-0.html' },
      history: { value: 'Discovered in 1817 by Johan August Arfvedson', link: 'https://www.chemblink.com/structure/3_3_0-0.html' },
      interestingFacts: { value: 'Lithium is the lightest metal and the lightest solid element.', link: 'https://www.chemblink.com/structure/3_3_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/3_3_0-0.html',
      group: 1,
      period: 2,
    },
    {
      name: { value: 'Beryllium', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'Be', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 4, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 9.0122, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.ALKALINE_EARTH_METALS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Beryllium is a chemical element with symbol Be and atomic number 4. It is a hard, grayish metal naturally found in mineral rocks, coal, soil, and volcanic dust.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.SOLID, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: 1287, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: 2471, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 2], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Used in aerospace materials and X-ray windows.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Discovered in 1798 by Louis-Nicolas Vauquelin.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Beryllium is used in making lightweight alloys for aircraft and missiles.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 2,
      period: 2,
    },
    {
      name: { value: 'Boron', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'B', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 5, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 10.81, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.METALLOIDS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Boron is a chemical element with symbol B and atomic number 5. It is a metalloid.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.SOLID, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: 2076, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: 4000, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 3], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Used in detergents, borosilicate glass, and semiconductors.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Boron was discovered by Joseph Louis Gay-Lussac and Louis-Jacques Thénard in 1808.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Boron is used in the manufacturing of fiberglass and ceramic products.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 13,
      period: 2,
    },
    {
      name: { value: 'Carbon', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'C', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 6, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 12.011, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.NONMETALS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Carbon is a chemical element with symbol C and atomic number 6. It is a nonmetal that can form various compounds.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.SOLID, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: 3915, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: 4027, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 4], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Used in the production of steel, fuels, and as a material in electronics and art.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Carbon has been known since ancient times and is present in all known life forms.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Carbon is the fourth most abundant element in the universe by mass.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 14,
      period: 2,
    },
    {
      name: { value: 'Nitrogen', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'N', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 7, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 14.007, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.NONMETALS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Nitrogen is a chemical element with symbol N and atomic number 7. It is a nonmetal and is a key component of the atmosphere.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.GAS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: -210.0, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: -195.8, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 5], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Used in fertilizers, explosives, and in the production of nitric acid.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Nitrogen was discovered by Daniel Rutherford in 1772.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Nitrogen makes up about 78% of Earth\'s atmosphere by volume.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 15,
      period: 2,
    },
    {
      name: { value: 'Oxygen', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'O', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 8, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 15.999, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.NONMETALS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Oxygen is a chemical element with symbol O and atomic number 8. It is essential for respiration and is the most abundant element in the Earth\'s crust.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.GAS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: -218.79, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: -182.96, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 6], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Used in respiration, combustion, water production, and as a medical support gas.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Oxygen was discovered by Joseph Priestley and Carl Wilhelm Scheele in the 1770s.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Oxygen makes up about 21% of Earth\'s atmosphere and is the most abundant element by mass in the Earth\'s crust.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 16,
      period: 2,
    },
    {
      name: { value: 'Fluorine', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'F', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 9, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 18.998, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.HALOGENS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Fluorine is a chemical element with symbol F and atomic number 9. It is highly reactive and is the most electronegative element.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.GAS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: -219.67, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: -188.11, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 7], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Used in the production of fluorides, refrigerants, and as a component in Teflon.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Fluorine was first isolated by Henri Moissan in 1886.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Fluorine is the most reactive and electronegative element, capable of reacting with almost every other element.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 17,
      period: 2,
    },
    {
      name: { value: 'Neon', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'Ne', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 10, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 20.180, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.NOBLE_GASES, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Neon is a chemical element with symbol Ne and atomic number 10. It is a colorless, odorless inert gas, and is used in neon signs.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.GAS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: -248.59, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: -246.08, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Used in neon signs and high-voltage indicators.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Neon was discovered in 1898 by William Ramsay and Morris W. Travers.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Neon signs are known for their bright colors, which are emitted when neon gas is electrically excited.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 18,
      period: 2,
    },
    {
      name: { value: 'Sodium', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'Na', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 11, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 22.9897, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.ALKALI_METALS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Sodium is a soft, silvery-white, highly reactive metal, and is one of the most abundant elements on Earth.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.SOLID, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: 97.72, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: 883, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8, 1], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Used in soap manufacturing and as a heat exchanger material.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Isolated in 1807 by Sir Humphry Davy.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Sodium vapor lamps are commonly used for street lighting.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 1,
      period: 3,
    },
    {
      name: { value: 'Magnesium', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'Mg', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 12, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 24.305, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.ALKALINE_EARTH_METALS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Magnesium is a shiny gray solid that is structurally quite similar to the other five alkaline earth metals.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.SOLID, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: 650, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: 1090, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8, 2], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Used in manufacturing of alloys, fireworks, and as a reducing agent in the production of titanium.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Discovered in 1755 by Joseph Black.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Magnesium is the eighth-most abundant element in the Earth\'s crust.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 2,
      period: 3,
    },
    {
      name: { value: 'Aluminum', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'Al', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 13, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 26.9815, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.METALS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Aluminum is a light, non-magnetic metal known for its strength and resistance to corrosion.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.SOLID, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: 660.32, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: 2519, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8, 3], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Used in aircraft, automobiles, packaging, and electrical conductors.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Discovered in 1825 by Hans Christian Ørsted.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Aluminum is the most abundant metal in the Earth\'s crust.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 13,
      period: 3,
    },
    {
      name: { value: 'Silicon', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'Si', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 14, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 28.085, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.METALLOIDS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Silicon is a semiconductor material used extensively in electronics and solar cells.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.SOLID, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: 1414, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: 2900, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8, 4], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Used in electronics, solar cells, and construction materials.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'First isolated in 1824 by Jöns Jacob Berzelius.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Silicon is the second most abundant element in the Earth\'s crust, after oxygen.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 14,
      period: 3,
    },
    {
      name: { value: 'Phosphorus', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'P', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 15, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 30.974, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.NONMETALS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Phosphorus is an essential element for life and is commonly found in fertilizers.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.SOLID, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: 44.15, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: 280, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8, 5], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Used in fertilizers, detergents, and matches.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Discovered by Hennig Brand in 1669.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Phosphorus was the first element to be chemically discovered.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 15,
      period: 3,
    },
    {
      name: { value: 'Sulfur', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'S', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 16, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 32.06, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.NONMETALS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Sulfur is a yellow, non-metal element that is commonly found in nature.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.SOLID, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: 115.21, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: 444.6, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8, 6], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Used in fertilizers, chemicals, and sulfuric acid production.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Known since ancient times, sulfur was used by the ancient Egyptians.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Sulfur is a key component of sulfuric acid, one of the most widely used industrial chemicals.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 16,
      period: 3,
    },
    {
      name: { value: 'Chlorine', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'Cl', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 17, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 35.45, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.NONMETALS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Chlorine is a yellow-green gas, used primarily as a disinfectant and in the production of various chemicals.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.GAS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: -101.5, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: -34.04, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8, 7], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Used in disinfectants, plastic production, and water treatment.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Discovered by Carl Wilhelm Scheele in 1774.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Chlorine is a powerful disinfectant and is widely used to treat drinking water and swimming pools.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 17,
      period: 3,
    },
    {
      name: { value: 'Argon', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'Ar', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 18, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 39.948, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.NOBLE_GASES, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Argon is a colorless, odorless, inert gas that makes up about 1% of the Earth\'s atmosphere.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.GAS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: -189.34, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: -185.85, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8, 8], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Used in light bulbs, welding, and as an inert gas in various industrial processes.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Discovered by Lord Rayleigh and William Ramsay in 1894.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Argon is the third most abundant gas in the Earth\'s atmosphere.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 18,
      period: 3,
    },
    {
      name: { value: 'Potassium', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'K', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 19, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 39.098, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.METALS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Potassium is a soft, silvery-white metal that is highly reactive, especially with water.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.SOLID, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: 63.5, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: 759, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8, 8, 1], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Used in fertilizers, fireworks, and as a salt substitute.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Discovered by Humphry Davy in 1807 through electrolysis of potassium hydroxide.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Potassium is an essential element for all living organisms and plays a key role in cellular functions.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 1,
      period: 4,
    },
    {
      name: { value: 'Calcium', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'Ca', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 20, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 40.078, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.METALS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Calcium is a soft, gray alkaline earth metal that is essential for life and abundant in the Earth\'s crust.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.SOLID, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: 842, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: 1484, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8, 8, 2], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Used in the production of cement, as a dietary supplement, and in metal alloys.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Discovered by Sir Humphry Davy in 1808 through the electrolysis of lime.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Calcium is crucial for bone health and muscle function in humans.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 2,
      period: 4,
    },
    {
      name: { value: 'Scandium', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'Sc', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 21, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 44.955, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.TRANSITION_METALS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Scandium is a soft, silvery-white metal that is found in trace amounts in certain minerals.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.SOLID, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: 1539, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: 2836, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8, 9, 2], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Used in aerospace components and in the production of lightweight aluminum alloys.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Discovered by Lars Fredrik Nilson in 1879, who isolated the element from a sample of euxenite.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Scandium is one of the rarest transition metals on Earth and has limited industrial applications.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 3,
      period: 4,
    },
    {
      name: { value: 'Titanium', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'Ti', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 22, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 47.867, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.TRANSITION_METALS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Titanium is a strong, low-density, and highly corrosion-resistant metal.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.SOLID, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: 1668, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: 3287, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8, 10, 2], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Used in aerospace, medical implants, and sports equipment due to its strength and low density.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Discovered by William Gregor in 1791, and named by Martin Heinrich Klaproth in 1795.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Titanium is as strong as steel but much lighter, making it an ideal material for aircraft and spacecraft.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 4,
      period: 4,
    },
    {
      name: { value: 'Vanadium', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'V', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 23, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 50.9415, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.TRANSITION_METALS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Vanadium is a transition metal used primarily to strengthen steel and enhance its corrosion resistance.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.SOLID, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: 1910, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: 3380, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8, 11, 2], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Used in steel manufacturing and as a catalyst in the production of sulfuric acid.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Discovered by Andrés Manuel del Río in 1801 and later confirmed by Nils Gabriel Sefström in 1830.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Vanadium is found in various minerals and is commonly used to make high-strength steel alloys.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 5,
      period: 4,
    },
    {
      name: { value: 'Chromium', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'Cr', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 24, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 52.0, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.TRANSITION_METALS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Chromium is a hard, shiny, and steel-gray metal that is highly valued for its corrosion resistance and hardness.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.SOLID, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: 1907, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: 2671, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8, 13, 1], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Used in stainless steel production and for plating to provide a shiny, corrosion-resistant surface.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Discovered by Louis-Nicolas Vauquelin in 1797.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Chromium is the element responsible for the shiny appearance of chrome-plated parts.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 6,
      period: 4,
    },
    {
      name: { value: 'Manganese', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'Mn', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 25, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 54.938044, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.TRANSITION_METALS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Manganese is a brittle, gray-white metal that is widely used in steel production and is an essential trace element in all living organisms.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.SOLID, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: 1244, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: 2095, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8, 13, 2], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Primarily used in the production of steel and alloys. Also used in batteries and as a catalyst.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Manganese was discovered by Johan Gottlieb Gahn in 1774.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Manganese is crucial for the production of iron and steel, making it one of the most important elements in metallurgy.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 7,
      period: 4,
    },
    {
      name: { value: 'Iron', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'Fe', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 26, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 55.845, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.TRANSITION_METALS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Iron is a metal that is commonly used for its strength and magnetic properties. It is an essential element in the human body as well.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.SOLID, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: 1538, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: 2862, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8, 14, 2], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Iron is mainly used in the production of steel, and as a key material in construction, tools, and machinery.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Iron has been used since ancient times, and its extraction from ore dates back to around 1200 BC.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Iron is the most widely used metal in the world, especially in the form of steel.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 8,
      period: 4,
    },
    {
      name: { value: 'Cobalt', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'Co', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 27, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 58.933, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.TRANSITION_METALS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Cobalt is a hard, lustrous metal used in the creation of strong alloys and in the battery industry. It is also essential for the production of vitamin B12 in living organisms.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.SOLID, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: 1495, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: 2927, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8, 15, 2], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Cobalt is used in the production of high-strength alloys and as a catalyst in the petroleum industry. It is also used in rechargeable batteries.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Cobalt was discovered by Georg Brandt in 1735.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Cobalt is used in rechargeable batteries like those in smartphones, laptops, and electric vehicles.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 9,
      period: 4,
    },
    {
      name: { value: 'Nickel', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'Ni', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 28, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 58.6934, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.TRANSITION_METALS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Nickel is a hard, silvery-white metal that is widely used in alloys and is an essential part of many rechargeable batteries.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.SOLID, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: 1455, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: 2913, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8, 16, 2], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Nickel is primarily used in the production of stainless steel, as well as in rechargeable batteries and catalysts.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Nickel was first isolated by Axel Fredrik Cronstedt in 1751.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Nickel is commonly used in coins and is also essential for the production of stainless steel.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 10,
      period: 4,
    },
    {
      name: { value: 'Copper', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'Cu', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 29, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 63.546, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.TRANSITION_METALS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Copper is a reddish-brown metal that is highly conductive and widely used in electrical wiring and plumbing systems.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.SOLID, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: 1084.62, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: 2562, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8, 18, 1], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Copper is primarily used in electrical wiring, plumbing, and as a material for coins. It is also used in alloys like bronze and brass.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Copper has been used by humans for over 10,000 years, making it one of the first metals to be used by ancient civilizations.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Copper is one of the few metals that occur naturally in pure form.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 11,
      period: 4,
    },    
    {
      name: { value: 'Zinc', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'Zn', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 30, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 65.38, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.TRANSITION_METALS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Zinc is a bluish-white metal used to galvanize other metals and to make alloys. It is also essential in biological functions and enzyme activity.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.SOLID, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: 419.58, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: 907, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8, 18, 2], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Zinc is primarily used in galvanization, the production of alloys like brass, and in batteries.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Zinc has been known since ancient times, although it was not used in its pure form until much later.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Zinc is used to prevent rust on steel and iron, making it important in infrastructure and machinery.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 12,
      period: 4,
    },
    {
      name: { value: 'Gallium', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'Ga', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 31, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 69.723, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.METALLOIDS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Gallium is a soft, silvery metal that is primarily used in semiconductors and optoelectronics.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.SOLID, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: 29.76, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: 2204, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8, 18, 3], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Gallium is used in semiconductors, LEDs, solar panels, and as a component in certain medical devices.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Gallium was discovered by Paul-Émile Lecoq de Boisbaudran in 1875.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Gallium can melt in your hand because its melting point is just above room temperature.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 13,
      period: 4,
    },
    {
      name: { value: 'Germanium', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'Ge', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 32, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 72.63, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.METALLOIDS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Germanium is a hard, grayish-white metalloid used in electronics and optical devices.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.SOLID, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: 938.25, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: 2833, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8, 18, 4], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Germanium is used in semiconductors, fiber optics, and infrared optics.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Germanium was discovered by Clemens Winkler in 1886.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Germanium is a key element in the manufacturing of solar panels and fiber optic cables.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 14,
      period: 4,
    },
    {
      name: { value: 'Arsenic', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'As', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 33, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 74.922, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.METALLOIDS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Arsenic is a metalloid that is toxic and has been used in pesticides and wood preservatives.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.SOLID, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: 817, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: 613, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8, 18, 5], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Arsenic is used in semiconductors, in some alloys, and as a wood preservative. It is also toxic to humans and animals.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Arsenic has been known since antiquity and has been used as a poison and in medicinal treatments for thousands of years.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Arsenic compounds are used in pesticides, but due to its toxicity, its use has been greatly restricted in recent years.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 15,
      period: 4,
    },
    {
      name: { value: 'Selenium', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'Se', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 34, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 78.971, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.NONMETALS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Selenium is a nonmetal that is chemically similar to sulfur and tellurium.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.SOLID, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: 221, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: 684, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8, 18, 6], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Selenium is used in photocells, solar cells, and in the glass industry.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Selenium was discovered in 1817 by Jöns Jacob Berzelius.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Selenium is an essential trace element for many forms of life.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 16,
      period: 4,
    },
    {
      name: { value: 'Bromine', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'Br', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 35, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 79.904, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.NONMETALS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Bromine is a halogen and the only nonmetallic element that is liquid at room temperature.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.LIQUID, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: -7.2, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: 58.8, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8, 18, 7], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Disinfectants, flame retardants', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Bromine was discovered in 1826 by Carl Jacob Löwig.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Bromine is the only nonmetal that is liquid at room temperature.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 17,
      period: 4,
    }, 
    {
      name: { value: 'Krypton', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'Kr', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 36, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 83.798, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.NOBLE_GASES, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Krypton is a colorless, odorless, tasteless noble gas that occurs in trace amounts in the Earth\'s atmosphere.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.GAS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: -157.4, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: -153.2, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8, 18, 8], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Lighting, photography, lasers', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Krypton was discovered in 1898 by William Ramsay and Morris Travers.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Krypton is used in some types of photographic flashes and in certain types of lasers.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 18,
      period: 4,
    },
    {
      name: { value: 'Rubidium', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'Rb', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 37, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 85.4678, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.METALS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Rubidium is a highly reactive, soft, silvery-white metallic element.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.SOLID, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: 39.31, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: 688, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8, 18, 8, 1], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Rubidium is used in research in chemistry and physics, particularly in atomic clocks.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Rubidium was discovered in 1861 by Robert Bunsen and Gustav Kirchhoff.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Rubidium is one of the least abundant elements in Earth\'s crust.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 1,
      period: 5,
    },
    {
      name: { value: 'Strontium', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      symbol: { value: 'Sr', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicNumber: { value: 38, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      atomicWeight: { value: 87.62, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      category: { value: ElementCategory.METALS, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      description: { value: 'Strontium is a soft, silvery-white or yellowish metallic element that is highly reactive chemically.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      stateAtRoomTemp: { value: ElementState.SOLID, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      meltingPoint: { value: 777, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      boilingPoint: { value: 1384, link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      electronConfiguration: { value: [2, 8, 18, 8, 2], link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      uses: { value: 'Strontium is used in producing ferrite magnets, in fireworks, and in medical imaging.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      history: { value: 'Strontium was discovered in 1790 by Adair Crawford from the mineral strontianite.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      interestingFacts: { value: 'Strontium compounds are responsible for the red color in fireworks.', link: 'https://www.chemblink.com/structure/1_1_0-0.html' },
      moreInfoLink: 'https://www.chemblink.com/structure/1_1_0-0.html',
      group: 2,
      period: 5,
    },    
    // Adicione outros elementos conforme necessário
  ];

  return elements;
};

const mockElements = createMockElements();
export default mockElements;
